[package]
name = "envelopers"
version = "0.7.0"
edition = "2021"
license-file = "LICENSE"
readme = "README.md"
description = "A very simple envelope encryption library using aes-gcm"
repository = "https://github.com/cipherstash/envelopers"

[dev-dependencies]
hex-literal = "0.3.2"
hex = "0.4.3"
tokio = { version = "1.17.0", features = [ "macros", "rt-multi-thread" ] }
http = "0.2"
base64 = "0.13.0"
futures = "0.3.21"
itertools = "0.10.3"

aws-smithy-client = { version = "0.40.2", features = [ "test-util" ] }
aws-smithy-http = "0.40.2"

[dependencies]
aes-gcm = "0.10.1"
rand = "0.8.5"
rand_chacha = "0.3.1"
serde = { version = "1.0.136", features = ["derive"] }
serde_cbor = "0.11.2"
thiserror = "1.0.30"
async-trait = "0.1.53"
lru = "0.7.5"
zeroize = { version = "1.5.5", features = [ "zeroize_derive" ] }
static_assertions = "1.1.0"

aws-sdk-kms = { version = "0.10.1", optional = true }
aws-config = { version = "0.10.1", optional = true }
async-mutex = "1.4.0"


[features]
default = ["aws-kms", "cache"]
# default = ["aws-kms"]
aws-kms = ["dep:aws-sdk-kms", "dep:aws-config"]
cache = []
tokio = ["aws-sdk-kms?/rt-tokio"]

[[example]]
name = "kms"
required-features = ["aws-kms", "cache"]

[[example]]
name = "kms-benchmark"
required-features = ["aws-kms", "cache"]
