[package]
name = "enveloper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dev-dependencies]
hex-literal = "0.3.2"
hex = "0.4.3"
tokio = { version = "1.17.0", features = [ "macros", "rt-multi-thread" ] }
aws-config = "0.9.0"

[dependencies]
aes-gcm = "0.9.4"
rand = "0.8.5"
rand_chacha = "0.3.1"
serde = { version = "1.0.136", features = ["derive"] }
serde_cbor = "0.11.2"
thiserror = "1.0.30"
async-trait = "0.1.53"
aws-sdk-kms = "0.9.0"
